apiVersion: v1
kind: Secret
metadata:
  name: env-secretkey
type: Opaque
stringData:
  DB_PASSWORD: "t4tEzkWzlg"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "demo-postgres-postgresql"
  DB_PORT: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: python-service
  name: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: python-service
  template:
    metadata:
      labels:
        service: python-service
    spec:
      containers:
        - image: 091578767186.dkr.ecr.us-east-1.amazonaws.com/udacity-thuy:4
          name: python-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: env-secretkey
            - configMapRef:
                name: env-configmap
      restartPolicy: Always